Name: php5_module
ConfigStart
	RULE_WANTHSREGEX=no
	RULE_HIDE=yes
	PHP_LIBS="  -rdynamic -Lmodules/php5 -L../modules/php5 -L../../modules/php5 -lmodphp5    -rdynamic -lcrypt   -lresolv -lcrypt -lmcrypt -lltdl -lpng -lz -ljpeg -lcurl -lbz2 -lz -lrt -lm -ldl  -lxml2 -lz -llzma -lm -ldl -lssl -lcrypto -lcurl -lxml2 -lz -llzma -lm -ldl -lxml2 -lz -llzma -lm -ldl -lcrypt -lxml2 -lz -llzma -lm -ldl -lssl -lcrypto -lcrypt  $LIBS"
	PHP_CFLAGS="$CFLAGS -I/usr/include -I/usr/src/php-5/main -I/usr/src/php-5/Zend -I/usr/src/php-5/TSRM -I/usr/src/php-5 -I/usr/src/php-5/sapi/apache -I/usr/src/php-5/main -I/usr/src/php-5/Zend -I/usr/src/php-5/TSRM"
	my_outfile="Makefile.config"
	echo "PHP_CFLAGS=$PHP_CFLAGS" >>$my_outfile
	echo "PHP_LIBS=$PHP_LIBS" >>$my_outfile
	LIBS=$PHP_LIBS
ConfigEnd
