#! /bin/sh

SED="/usr/bin/sed"
prefix="/usr/local"
datarootdir="/usr/local/php"
exec_prefix="${prefix}"
version="5.6.40-r7-janforman.com"
vernum="50640"
include_dir="${prefix}/include/php"
includes="-I$include_dir -I$include_dir/main -I$include_dir/TSRM -I$include_dir/Zend -I$include_dir/ext -I$include_dir/ext/date/lib"
ldflags=" -rdynamic"
libs="-lcrypt   -lresolv -lcrypt -lmcrypt -lltdl -lpng -lz -ljpeg -lcurl -lbz2 -lz -lrt -lm -ldl  -lxml2 -lz -llzma -lm -ldl -lssl -lcrypto -lcurl -lxml2 -lz -llzma -lm -ldl -lxml2 -lz -llzma -lm -ldl -lcrypt -lxml2 -lz -llzma -lm -ldl -lssl -lcrypto -lcrypt "
extension_dir='/usr/local/lib/php/extensions/no-debug-non-zts-20131226'
man_dir=`eval echo ${datarootdir}/man`
program_prefix=""
program_suffix=""
exe_extension=""
php_cli_binary=NONE
php_cgi_binary=NONE
configure_options=" '--enable-exif' '--with-openssl' '--disable-phar' '--disable-flatfile' '--disable-sysvshm' '--disable-sysvmsg' '--disable-sysvsem' '--disable-sockets' '--disable-xmlreader' '--disable-xmlwriter' '--disable-posix' '--disable-pdo' '--disable-wddx' '--disable-cli' '--disable-debug' '--disable-pcntl' '--with-gd' '--with-zlib' '--with-bz2' '--enable-inline-optimization' '--without-gmp' '--without-kerberos' '--without-xmlrpc' '--with-iconv' '--with-pic' '--with-mysql' '--with-mysqli' '--with-jpeg-dir=/usr/lib' '--enable-mbstring' '--without-pear' '--without-sqlite3' '--without-snmp' '--with-mcrypt' '--with-curl' '--with-libdir=/lib64' '--with-apache=../apache_1.3.42' 'CFLAGS=-Os '-march=native' '-pipe' '-fforce-addr' '-fomit-frame-pointer' '-fexpensive-optimizations' '-ffast-math''"
php_sapis=" apache cgi"

# Set php_cli_binary and php_cgi_binary if available
for sapi in $php_sapis; do
  case $sapi in
  cli)
    php_cli_binary="${exec_prefix}/bin/${program_prefix}php${program_suffix}${exe_extension}"
    ;;
  cgi)
    php_cgi_binary="${exec_prefix}/bin/${program_prefix}php-cgi${program_suffix}${exe_extension}"
    ;;
  esac
done

# Determine which (if any) php binary is available
if test "$php_cli_binary" != "NONE"; then
  php_binary="$php_cli_binary"
else
  php_binary="$php_cgi_binary"
fi

# Remove quotes
configure_options=`echo $configure_options | $SED -e "s#'##g"`

case "$1" in
--prefix)
  echo $prefix;;
--includes)
  echo $includes;;
--ldflags)
  echo $ldflags;;
--libs)
  echo $libs;;
--extension-dir)
  echo $extension_dir;;
--include-dir)
  echo $include_dir;;
--php-binary)
  echo $php_binary;;
--php-sapis)
  echo $php_sapis;;
--configure-options)
  echo $configure_options;;
--man-dir)
  echo $man_dir;;
--version)
  echo $version;;
--vernum)
  echo $vernum;;
*)
  cat << EOF
Usage: $0 [OPTION]
Options:
  --prefix            [$prefix]
  --includes          [$includes]
  --ldflags           [$ldflags]
  --libs              [$libs]
  --extension-dir     [$extension_dir]
  --include-dir       [$include_dir]
  --man-dir           [$man_dir]
  --php-binary        [$php_binary]
  --php-sapis         [$php_sapis]
  --configure-options [$configure_options]
  --version           [$version]
  --vernum            [$vernum]
EOF
  exit 1;;
esac

exit 0
